name: Test PR on main

env:
  ATLAS_URL: ${{secrets.ATLAS_URL}}
  DB_NAME: ${{secrets.DB_NAME}}
  
on:
  pull_request:
    branches:
      - main

jobs:
  test-main-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest
